#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# config/routes.yaml


api_upload_image:
  path: /api/upload-image
  controller: App\MyHelpers\ImageSaverForJava::uploadImage
  methods: [POST]